var accountDetails = "<div class='account-details-main-address'><div class='account-details-main-address-head'></div>";
	accountDetails += "<div class='account-details-main-address-head-content'><div class='address-loading-image'><img src='<?php echo linkToPlugin?>css/img/icon/loading_icon.gif' width='500px'></div></div>";
	accountDetails += "<div class='account-details-below '><div id='account-details-tabs'><ul class='ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all'><li class='ui-state-default ui-corner-top ui-tabs-selected ui-state-active'><a href='#account-details-tabs-1'>Accounts</a></li><li class='ui-state-default ui-corner-top'><a href='#account-details-tabs-2'>Payment Details</a></li><li class='ui-state-default ui-corner-top'><a href='#account-details-tabs-3'>Settings</a></li></ul>";	
	accountDetails += "<div class='ui-tabs-panel ui-widget-content ui-corner-bottom' id='account-details-tabs-1'></div>";		     
	accountDetails += "<div class='ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide' id='account-details-tabs-2'><div class='ccount-details-payment-head'>Payment Details</div><div class='account-details-payment-type'><div class='account-details-payment-img'><img src='<?php echo linkToPlugin?>css/img/directdebit_logo.jpg' width='80' height='28'></div><div class='account-details-payment-contact'>Direct Debit<br>Account: ******25<br>Valid to:<br>Name: Name, Surname</div><div class='is-bottons account-details-payment-button'>Delete</div><div class='is-bottons account-details-payment-button'>Edit</div></div><div class='account-details-payment-bottom'><div class='is-bottons account-details-payment-button new-payment-button'>New Payment Method</div></div></div>";		
	accountDetails += "<div class='ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide' id='account-details-tabs-3'><div class='account-details-settings'><div class='account-details-settings-cell'>&nbsp;</div><div class='account-details-settings-cell'><input type='checkbox' class='input-check-box'></div><div class='account-details-settings-cell'><select class='account-details-settings-options-select'><option>EUR</option><option>USD</option><option>VND</option></select></div> <div class='account-details-settings-cell'><select class='account-details-settings-options-select'><option>EN</option><option>DE</option><option>VI</option></select></div>";
	accountDetails += "<div class='account-details-settings-cell'><input type='checkbox' class='input-check-box'></div><div class='account-details-settings-cell'><select class='account-details-settings-options-select'><option>50</option><option>100</option><option>150</option></select></div></div><div class='account-details-settings-setting'><div class='account-details-settings-setting-cell'><strong>Setting</strong></div><div class='account-details-settings-setting-cell'>Newsletter</div><div class='account-details-settings-setting-cell'>Currency</div><div class='account-details-settings-setting-cell'>Language</div><div class='account-details-settings-setting-cell'>Address</div><div class='account-details-settings-setting-cell'>Jobs per page</div>";	
	accountDetails += "</div><div class='account-details-settings-description'><div class='account-details-settings-description-cell'><strong>Description</strong></div><div class='account-details-settings-description-cell'>Get the newest infomation</div><div class='account-details-settings-description-cell'>Choose your prefered currency</div><div class='account-details-settings-description-cell'>Choose your prefered Language</div><div class='account-details-settings-description-cell'>Saving your prefered Address</div><div class='account-details-settings-description-cell'>How many jobs should be shown per page ?</div></div>";
	accountDetails += "<div class='account-details-connection-bottom'><div style='margin-top: 10px;'>Something is missing ? We love your feedback. We're always looking to improve our experience so please let us know what you think </div><div class='account-details-connection-bottom-divide'>We love feedback. We're always looking to improve our experience so please let us know what you think</div><div class='is-bottons account-details-connection-bottom-add'>Delete</div></div></div></div></div>";
					
//append to address book page
jQuery('.account-details-container').empty();
jQuery('.account-details-container').append(accountDetails);
//countriesGet();